language: python

python: 2.7

env:
  - TOXENV=py27-django17
  - TOXENV=py27-django18
  - TOXENV=py33-django17
  - TOXENV=py33-django18
  - TOXENV=py34-django17
  - TOXENV=py34-django18
  - TOXENV=py34-django19
  - TOXENV=py35-django18
  - TOXENV=py35-django19

install:
  - pip install tox

script:
  - tox

matrix:
  allow_failures:
    - env: TOXENV=py35-django18
    - env: TOXENV=py35-django19
